language: go

dist: trusty
sudo: false

os:
  - linux

services:
  - mongodb

#gobuild_args: '--ldflags "-X \"main.version=$TRAVIS_TAG\" -X \"main.build=$(git rev-parse --short HEAD)\" -X \"main.buildDate=$(date --rfc-3339=seconds)\""'

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
    - pandoc
   

go:
  - 1.6.3
  - 1.7.3
  - tip

matrix:
  allow_failures:
    - go: tip

#branches:
#  only:
#  - master
#  - develop
#  - /^v*.*.*$/

#env:
#  global:
#    - GOARCH=amd64

notifications:
  email:
    on_success: change
    on_failure: always

#before_install:
#  - go env

install:
 - go get -t ./...
 - go get -u github.com/stretchr/testify/assert
 - go get -u github.com/golang/lint/golint
 - go get -u golang.org/x/tools/cmd/goimports
 - go get -u golang.org/x/tools/cmd/cover
 - go get -u github.com/mattn/goveralls
 - go get -u github.com/erikstmartin/go-testdb

before_script:
#  - sleep 1

script:
 - go vet ./...
 - diff <(goimports -d .) <(printf "")
 - diff <(golint ./...) <(printf "")
 - go test -v -covermode=count -coverprofile=coverage.out
 - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
# - go test -v -cpu=2 -short ./...
# - go test -v -cpu=1,2,4 -short ./...

#after_script:

#after_success:
#  - go env && pwd

#after_failure:
#  - go env && pwd


before_deploy:
  - echo 'Deploing started'
  - mkdir release
  - pandoc README.md -f markdown_github -t html -s -o README.html
  - cp config.smpl.yml config.yml
#  - export GO_BILD_LDFLAGS='-X \"main.version=$TRAVIS_TAG\" -X \"main.build=$(git rev-parse --short HEAD)\" -X \"main.buildDate=$(date --rfc-3339=seconds)\"'
# --ldflags "$GO_BILD_LDFLAGS" 
  - GOARCH=amd64 GOOS=linux; go env; go build -v -o als-go; tar -zcvf release/als-go-linux-amd64_g$TRAVIS_GO_VERSION.tar.gz als-go README.html config.yml init.d-alsgo
  - export GOARCH=386 && export GOOS=linux && go env && go build -v -o als-go && tar -zcvf release/als-go-linux-i386_g$TRAVIS_GO_VERSION.tar.gz als-go README.html config.yml init.d-alsgo
  - export GOARCH=arm && export GOOS=linux && go env && go build -v -o als-go && tar -zcvf release/als-go-linux-arm_g$TRAVIS_GO_VERSION.tar.gz als-go README.html config.yml init.d-alsgo
  - export GOARCH=arm64 && export GOOS=linux && go env && go build -v -o als-go && tar -zcvf release/als-go-linux-arm64_g$TRAVIS_GO_VERSION.tar.gz als-go README.html config.yml init.d-alsgo
  - export GOARCH=ppc64 && export GOOS=linux && go env && go build -v -o als-go && tar -zcvf release/als-go-linux-ppc64_g$TRAVIS_GO_VERSION.tar.gz als-go README.html config.yml init.d-alsgo
  - export GOARCH=s390x && export GOOS=linux && go env && go build -v -o als-go && tar -zcvf release/als-go-linux-s390x_g$TRAVIS_GO_VERSION.tar.gz als-go README.html config.yml init.d-alsgo
#  - export CGO_ENABLED=1
  - export GOARCH=amd64 && export GOOS=windows && go env && go build -v -o als-go.exe && zip release/als-go-windows-amd64_g$TRAVIS_GO_VERSION.zip als-go.exe README.html config.yml
  - export GOARCH=386 && export GOOS=windows && go env && go build -v -o als-go.exe && zip release/als-go-windows-386_g$TRAVIS_GO_VERSION.zip als-go.exe README.html config.yml
  - ls -1 $(go env GOROOT)/pkg
  
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - "release/als-go-windows-amd64_g$TRAVIS_GO_VERSION.zip"
      - "release/als-go-windows-386_g$TRAVIS_GO_VERSION.zip"
      - "release/als-go-linux-i386_g$TRAVIS_GO_VERSION.tar.gz"
      - "release/als-go-linux-amd64_g$TRAVIS_GO_VERSION.tar.gz"
      - "release/als-go-linux-arm_g$TRAVIS_GO_VERSION.tar.gz"
      - "release/als-go-linux-arm64_g$TRAVIS_GO_VERSION.tar.gz"
      - "release/als-go-linux-ppc64_g$TRAVIS_GO_VERSION.tar.gz"
      - "release/als-go-linux-s390x_g$TRAVIS_GO_VERSION.tar.gz"

    on:
      repo: RiftBit/ALS-Go
      tags: true
      #go: 1.7.3
      all_branches: true

after_deploy:
  - echo 'Deploing finished!'
