
system:
  maxThreads: 250
  listenOn: ":8080"

admin:
  rootUser: "ergoz"
  rootPassword: "123"
  rootEmail: "ergozru@gmail.com"

db:
  #[username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]
  dbConnectionString: "als-go:p@ssword@tcp(172.16.104.21:3306)/als-go?charset=utf8"

log:
  formatter: "text"
  logLevel: "info"

mongo:
  connectionTimeout: 1000 #msec
  commonDB:
    connection: "172.16.104.228:27017"

  additionalDB:
    -
      connection: "172.16.104.255:27017"
      collections: ["customer_log","archive_customer_contract","archive_customer_data", "archive_customer_log", "monitor"]
  #  -
  #    connection: "192.168.99.100:27019"
  #    collections: ["internal_error","main_error"]