
system:
  maxThreads: 250
  listenOn: ":8080"

admin:
  rootUser: "ergoz"
  rootPassword: "123"
  rootEmail: "ergozru@gmail.com"

db:
  #[username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]
  dbConnectionString: "als-go:xsw2zaq1@tcp(192.168.175.44:3306)/als-go?charset=utf8"

mongo:
  connectionTimeout: 1000 #msec
  commonDB:
    connection: "192.168.175.44:27017"

  additionalDB:
  #  -
  #    connection: "192.168.99.100:27018"
  #    collections: ["capi","bapi_request"]
  #  -
  #    connection: "192.168.99.100:27019"
  #    collections: ["internal_error","main_error"]