system:
  maxThreads: 250
  listenOn: ":8080"

admin:
  rootUser: "ergoz"
  rootPassword: "123"
  rootEmail: "ergozru@gmail.com"

db:
  #[username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]
  dbConnectionString: "als-go:p@ssword@tcp(172.16.104.21:3306)/als-go?charset=utf8"

log:
  formatter: "text"
  logLevel: "info"
  disableColors: true
  timestampFormat: "2006-01-02T15:04:05.999999999Z07:00"

# Allowed formats
#ANSIC       = "Mon Jan _2 15:04:05 2006"
#UnixDate    = "Mon Jan _2 15:04:05 MST 2006"
#RubyDate    = "Mon Jan 02 15:04:05 -0700 2006"
#RFC822      = "02 Jan 06 15:04 MST"
#RFC822Z     = "02 Jan 06 15:04 -0700" // RFC822 with numeric zone
#RFC850      = "Monday, 02-Jan-06 15:04:05 MST"
#RFC1123     = "Mon, 02 Jan 2006 15:04:05 MST"
#RFC1123Z    = "Mon, 02 Jan 2006 15:04:05 -0700" // RFC1123 with numeric zone
#RFC3339     = "2006-01-02T15:04:05Z07:00"
#RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
#Kitchen     = "3:04PM"
# Handy time stamps.
#Stamp      = "Jan _2 15:04:05"
#StampMilli = "Jan _2 15:04:05.000"
#StampMicro = "Jan _2 15:04:05.000000"
#StampNano  = "Jan _2 15:04:05.000000000"

mongo:
  connectionTimeout: 10000 #msec
  commonDB:
    connection: "172.16.104.228:27017"

  additionalDB:
    -
      connection: "172.16.104.255:27017"
      collections: ["customer_log","archive_customer_contract","archive_customer_data", "archive_customer_log", "monitor"]
  #  -
  #    connection: "192.168.99.100:27019"
  #    collections: ["internal_error","main_error"]